name: build
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Activate Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: control
          environment-file: environment.yml

      - name: Display FFMPEG Info
        run: ffmpeg -version

      - name: HTML & Assets Build
        run: python build.py

      - name: Deployment Setup
        run: rm .gitignore

      - name: Deployment
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "."
          SINGLE_COMMIT: true
          PRESERVE: true
